name = "tangle-tools-router"
main = "src/index.ts"
compatibility_date = "2026-03-01"

routes = [
  { pattern = "tangle.tools/blog", zone_name = "tangle.tools" },
  { pattern = "tangle.tools/blog/*", zone_name = "tangle.tools" },
  { pattern = "tangle.tools/post", zone_name = "tangle.tools" },
  { pattern = "tangle.tools/post/*", zone_name = "tangle.tools" },
  { pattern = "tangle.tools/feed.xml", zone_name = "tangle.tools" },
  { pattern = "tangle.tools/sitemap.xml", zone_name = "tangle.tools" },
  { pattern = "tangle.tools/images/*", zone_name = "tangle.tools" },
  { pattern = "tangle.tools/_next/*", zone_name = "tangle.tools" },
  { pattern = "tangle.tools/og", zone_name = "tangle.tools" },
  { pattern = "tangle.tools/og/*", zone_name = "tangle.tools" },

  { pattern = "www.tangle.tools/blog", zone_name = "tangle.tools" },
  { pattern = "www.tangle.tools/blog/*", zone_name = "tangle.tools" },
  { pattern = "www.tangle.tools/post", zone_name = "tangle.tools" },
  { pattern = "www.tangle.tools/post/*", zone_name = "tangle.tools" },
  { pattern = "www.tangle.tools/feed.xml", zone_name = "tangle.tools" },
  { pattern = "www.tangle.tools/sitemap.xml", zone_name = "tangle.tools" },
  { pattern = "www.tangle.tools/images/*", zone_name = "tangle.tools" },
  { pattern = "www.tangle.tools/_next/*", zone_name = "tangle.tools" },
  { pattern = "www.tangle.tools/og", zone_name = "tangle.tools" },
  { pattern = "www.tangle.tools/og/*", zone_name = "tangle.tools" }
]

[vars]
BLOG_ORIGIN = "https://tangle-blog.pages.dev"
